### Rust Module
#### rust_module/Cargo.toml

[package]
name = "rust_module"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"] }
